name: Compile

on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  compile:
    name: Compile Hugo
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        include:
          - type: standard
            platform: linux/amd64

          - type: standard
            platform: linux/arm/v7

          - type: standard
            platform: linux/arm64/v8

          - type: extended
            platform: linux/amd64

          - type: extended
            platform: linux/arm/v7

          - type: extended
            platform: linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Load variables
        run: make load-vars
        env:
          LOAD_HUGO_TYPE: ${{ matrix.type }}

      - name: Extract platform variables
        run: make extract-platform
        env:
          HUGO_PLATFORM: ${{ matrix.platform }}

      - name: Pull Docker image
        run: make docker-pull

      - name: Load arch identifier
        run: make arch

      - name: Fetch Hugo source
        run: make checkout
        env:
          HUGO_BRANCH: v${{ env.HUGO_VERSION }}

      - name: Compile
        run: make compile
        env:
          HUGO_VENDOR: ${{ github.repository_owner }}

      - name: Copy resources
        run: make copy

      - name: Create tar.gz
        run: make package

      - name: Generate checksum
        run: make generate-checksum

      - name: Upload bundle (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.TARGET_BUNDLE }}
          name: hugo-${{ matrix.type }}-${{ env.HUGO_VERSION }}-linux-${{ env.HUGO_ARCH }}.tar.gz
          label: Hugo ${{ env.HUGO_VERSION }}, ${{ matrix.type }} edition (Linux ${{ env.HUGO_ARCH }})

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.TARGET_BUNDLE }}
          name: hugo-${{ env.HUGO_VERSION }}-dist
          retention-days: 5

      - name: Upload checksum (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: target/checksums/*
          name: checksums


  checksums:
    name: Checksums file
    runs-on: ubuntu-latest
    needs: compile
    
    strategy:
      matrix:
        alg:
          - sha256
          - sha512

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Load variables
        run: make load-vars
        
      - name: Download checksums
        uses: actions/download-artifact@v2
        with:
          name: checksums
          path: checksums
      
      - name: Geneate checksums file
        run: make generate-checksums
        env:
          CHECKSUM_ALG: ${{ matrix.alg }}

      - name: Upload checksums (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.TARGET_CHECKSUMS }}
          name: hugo-${{ env.HUGO_VERSION }}-checksums-${{ matrix.alg }}.txt
          label: Hugo ${{ env.HUGO_VERSION }}, checksums (${{ matrix.alg }})

      - name: Upload checksums (artifacs)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.TARGET_CHECKSUMS }}
          name: hugo-${{ env.HUGO_VERSION }}-dist
          retention-days: 3

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: checksums

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Load variables
        run: make load-vars
        
      - name: Download checksums
        uses: actions/download-artifact@v2
        with:
          name: hugo-${{ env.HUGO_VERSION }}-dist
          path: dist

      - name: Verify distribution
        run: make verify