name: Compile

on:
  workflow_dispatch:

jobs:
  compile:
    name: Compile Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Load environment variables
        uses: k15g/action-load-env@v1
        with:
          extras: |
            HUGO_TYPE=${{ matrix.type }}

      - name: Extract platform variables
        run: make extract-platform
        env:
          HUGO_PLATFORM: ${{ matrix.platform }}

      - name: Pull Docker image
        run: make docker-pull

      - name: Load arch identifier
        run: make arch

      - name: Fetch Hugo source
        run: make checkout
        env:
          HUGO_BRANCH: v${{ env.HUGO_VERSION }}

      - name: Compile
        run: make compile
        env:
          HUGO_VENDOR: ${{ github.repository_owner }}
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: arm64

      - name: Copy resources
        run: make copy

      - name: Create tar.gz
        run: make package-bundle

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.TARGET_BUNDLE }}
          name: hugo*dist*
