name: Compile

on:
  push:
    paths-ignore:
      - .github/**
      - .gitignore
      - LICENSE
      - README.md
    branches:
      - main
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  compile:
    name: Compile Hugo
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        include:
          - type: standard
            platform: linux/amd64

          - type: standard
            platform: linux/arm/v7

          - type: standard
            platform: linux/arm64/v8

          - type: extended
            platform: linux/amd64

          - type: extended
            platform: linux/arm/v7

          - type: extended
            platform: linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Load environment variables
        uses: k15g/action-load-env@edge
        with:
          extras: |
            HUGO_TYPE=${{ matrix.type }}

      - name: Extract platform variables
        run: make extract-platform
        env:
          HUGO_PLATFORM: ${{ matrix.platform }}

      - name: Pull Docker image
        run: make docker-pull

      - name: Load arch identifier
        run: make arch

      - name: Fetch Hugo source
        run: make checkout
        env:
          HUGO_BRANCH: v${{ env.HUGO_VERSION }}

      - name: Compile
        run: make compile
        env:
          HUGO_VENDOR: ${{ github.repository_owner }}

      - name: Copy resources
        run: make copy

      - name: Create tar.gz
        run: make package-bundle

      - name: Upload bundle (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.TARGET_BUNDLE }}
          name: hugo-${{ matrix.type }}-${{ env.HUGO_VERSION }}-linux-${{ env.HUGO_ARCH }}.tar.gz
          label: Hugo ${{ env.HUGO_VERSION }}, ${{ matrix.type }} edition (Linux ${{ env.HUGO_ARCH }})

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.TARGET_BUNDLE }}
          name: hugo-${{ env.HUGO_VERSION }}-dist
          retention-days: 3


  checksums:
    name: Checksum file (sha)
    runs-on: ubuntu-latest
    needs: compile
    
    strategy:
      matrix:
        alg:
          - 256
          - 512

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load environment variables
        uses: k15g/action-load-env@edge

      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: hugo-${{ env.HUGO_VERSION }}-dist
          path: dist

      - name: Generate checksums
        env:
          TARGET_CHECKSUMS: target/hugo-${{ env.HUGO_VERSION }}-checksums-sha${{ matrix.alg }}.txt
        run: |
          mkdir -p $(dirname $TARGET_CHECKSUMS)
          cd dist && shasum -a ${{ matrix.alg }} * > ../$TARGET_CHECKSUMS

      - name: Upload checksums (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_CHECKSUMS: target/hugo-${{ env.HUGO_VERSION }}-checksums-sha${{ matrix.alg }}.txt
        with:
          file: ${{ env.TARGET_CHECKSUMS }}
          label: Hugo ${{ env.HUGO_VERSION }}, checksums (sha${{ matrix.alg }})

      - name: Upload checksums (artifacs)
        uses: actions/upload-artifact@v2
        env:
          TARGET_CHECKSUMS: target/hugo-${{ env.HUGO_VERSION }}-checksums-sha${{ matrix.alg }}.txt
        with:
          path: ${{ env.TARGET_CHECKSUMS }}
          name: hugo-${{ env.HUGO_VERSION }}-dist
          retention-days: 3
