name: Compile

on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - type: standard
            arch: amd64
            platform: linux/amd64

          - type: standard
            arch: aarch64
            platform: linux/arm64/v8

          - type: extended
            arch: amd64
            platform: linux/amd64

          - type: extended
            arch: aarch64
            platform: linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Load variables
        run: make load-vars

      - name: Extract platform variables
        run: make extract-platform
        env:
          HUGO_PLATFORM: ${{ matrix.platform }}

      - name: Pull Docker image
        run: make docker-pull

      - name: Fetch Hugo source
        run: make checkout

      - name: Compile
        run: make compile
        env:
          HUGO_TYPE: ${{ matrix.type }}
          HUGO_VENDOR: ${{ github.actor }}

      - name: Copy resources
        run: make copy

      - name: Create tar.gz
        run: make package

      - name: Upload package
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/bundle.tar.gz
          name: hugo-${{ matrix.type }}-${{ matrix.arch }}.tar.gz
          label: Hugo ${{ matrix.type }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: hugo-${{ matrix.type }}-${{ matrix.arch }}
          path: target/bundle.tar.gz