name: Compile

on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  compile:
    name: Compile Hugo
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        include:
          - type: standard
            arch: amd64
            platform: linux/amd64

          - type: standard
            arch: aarch64
            platform: linux/arm64/v8

          - type: extended
            arch: amd64
            platform: linux/amd64

          - type: extended
            arch: aarch64
            platform: linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Load variables
        run: make load-vars
        env:
          LOAD_HUGO_TYPE: ${{ matrix.type }}
          LOAD_HUGO_ARCH: ${{ matrix.arch }}

      - name: Extract platform variables
        run: make extract-platform
        env:
          HUGO_PLATFORM: ${{ matrix.platform }}

      - name: Pull Docker image
        run: make docker-pull

      - name: Fetch Hugo source
        run: make checkout
        env:
          HUGO_BRANCH: v${{ env.HUGO_VERSION }}

      - name: Compile
        run: make compile
        env:
          HUGO_VENDOR: ${{ github.repository_owner }}

      - name: Copy resources
        run: make copy

      - name: Create tar.gz
        run: make package

      - name: Generate checksum
        run: make generate-checksum

      - name: Upload bundle (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.TARGET_BUNDLE }}
          name: hugo_${{ matrix.type }}_${{ env.HUGO_VERSION }}_${{ matrix.arch }}.tar.gz
          label: Hugo ${{ env.HUGO_VERSION }}, ${{ matrix.type }} edition (${{ matrix.arch }})

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          path: ${{ env.TARGET_BUNDLE }}
          name: hugo_${{ matrix.type }}_${{ env.HUGO_VERSION }}_${{ matrix.arch }}

      - name: Upload checksum (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.TARGET_CHECKSUM }}
          name: checksums.sha256


  checksums:
    name: Checksum file
    runs-on: ubuntu-latest
    needs: compile
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Load variables
        run: make load-vars
        
      - name: Download checksums
        uses: actions/download-artifact@v2
        with:
          name: checksums.sha256
          path: checksums
      
      - name: Geneate checksums file
        run: make generate-checksums

      - name: Upload checksums (release)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.TARGET_CHECKSUMS }}
          name: hugo_${{ env.HUGO_VERSION }}_checksums.txt
          label: Hugo ${{ env.HUGO_VERSION }}, checksums (sha256)

      - name: Upload checksums (artifacs)
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          path: ${{ env.TARGET_CHECKSUMS }}
          name: hugo_${{ env.HUGO_VERSION }}_checksums