name: Docker build

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker experimental
        run: make enable-docker-experimental

#      - name: Docker login
#        uses: docker/login-action@v1
#        with:
#          username: klakegg
#          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Fetch Hugo source
        run: make checkout

      - name: Build
        run: make build

      - name: Copy resources
        run: make copy